force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assen</fullName>
            </value>
            <value>
                <fullName>Coevorden</fullName>
            </value>
            <value>
                <fullName>Emmen</fullName>
            </value>
            <value>
                <fullName>Hoogeveen</fullName>
            </value>
            <value>
                <fullName>Meppel</fullName>
            </value>
            <value>
                <fullName>Almere</fullName>
            </value>
            <value>
                <fullName>Biddinghuizen</fullName>
            </value>
            <value>
                <fullName>Emmeloord</fullName>
            </value>
            <value>
                <fullName>Lelystad</fullName>
            </value>
            <value>
                <fullName>Bolsward</fullName>
            </value>
            <value>
                <fullName>Dokkum</fullName>
            </value>
            <value>
                <fullName>Franeker</fullName>
            </value>
            <value>
                <fullName>Harlingen</fullName>
            </value>
            <value>
                <fullName>Hindeloopen</fullName>
            </value>
            <value>
                <fullName>IJlst</fullName>
            </value>
            <value>
                <fullName>Leeuwarden</fullName>
            </value>
            <value>
                <fullName>Sloten</fullName>
            </value>
            <value>
                <fullName>Sneek</fullName>
            </value>
            <value>
                <fullName>Stavoren</fullName>
            </value>
            <value>
                <fullName>Workum</fullName>
            </value>
            <value>
                <fullName>Apeldoorn</fullName>
            </value>
            <value>
                <fullName>Arnhem</fullName>
            </value>
            <value>
                <fullName>Bredevoort</fullName>
            </value>
            <value>
                <fullName>Buren</fullName>
            </value>
            <value>
                <fullName>Borculo</fullName>
            </value>
            <value>
                <fullName>Culemborg</fullName>
            </value>
            <value>
                <fullName>Dieren</fullName>
            </value>
            <value>
                <fullName>Doetinchem</fullName>
            </value>
            <value>
                <fullName>Ede</fullName>
            </value>
            <value>
                <fullName>Elburg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier__c/fields/Supplier_Url__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Url__c</fullName>
    <formula>&apos;/lightning/r/Supplier/&apos;+Id+&apos;/view&apos;</formula>
    <label>Supplier Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetSupplierController.cls
public class GetSupplierController {
    
    @AuraEnabled(Cacheable = true)
    public static List<Supplier__c> searchSuppliers(String strCityName) {
        strCityName = '%' + strCityName + '%';
        List<Supplier__c> supplierList = new List<Supplier__c>();
        try{
            supplierList = [SELECT Id, Name, City__c, Coordinates__Latitude__s, Coordinates__Longitude__s,
                                          Address__Street__s, Address__City__s, Address__StateCode__s,
                                          Address__CountryCode__s, Address__PostalCode__s, Address__GeocodeAccuracy__s, 
                                          Address__Latitude__s, Address__Longitude__s, Address__c, Supplier_Url__c  
                                          FROM Supplier__c WHERE City__c LIKE:strCityName];
        } catch(Exception e){
            system.debug('Exception is : ' + e.getMessage());
        }
        return supplierList; 
    }
    
    @AuraEnabled(Cacheable = true)
    public static Account getAccountCity(Id recordId) {
        Account accountObj = new Account();
        try{
            accountObj = [SELECT Id, BillingCity FROM Account WHERE ID =:recordId LIMIT 1];
        }
        catch(Exception e){
            system.debug('Exception is : ' + e.getMessage());
        }
        return accountObj; 
    }
}