force-app/main/default/objects/Account/fields/CS_Rating__c.field-meta.xml
<CustomField>
    <fullName>CS_Rating__c</fullName>
    <label>CS Rating</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CSR__c.field-meta.xml
<CustomField>
    <fullName>CSR__c</fullName>
    <label>CSR</label>
    <precision>5</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Satisfaction_Rating__c.field-meta.xml
<CustomField>
    <fullName>Customer_Satisfaction_Rating__c</fullName>
    <description>Customer Satisfaction Rating of cases of the customer</description>
    <label>Customer Satisfaction Rating</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_Satisfaction_Rating__c.field-meta.xml
<CustomField>
    <fullName>Customer_Satisfaction_Rating__c</fullName>
    <label>Customer Satisfaction Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHelperTest.cls
@isTest
public class CaseTriggerHelperTest {
    
    @testSetup static void setup() {
        // Create common test accounts
        List<Account> testAccts = new List<Account>();
        for(Integer i=0;i<2;i++) {
            testAccts.add(new Account(Name = 'TestAcct'+i));
        }
        insert testAccts; 
        
        List<Case> testCases = new List<Case>();
        for(Integer i=0;i<2;i++) {
            testCases.add(new Case(Status='New',
                                  AccountId=testAccts[i].Id));
        }
        insert testCases; 
    }
    
    @isTest static void afterInsertTest() {
        
        Account acct = [SELECT Id, CSR__c, CS_Rating__c, Account.Name FROM Account WHERE Name='TestAcct0' LIMIT 1];
        Case caseObj = [SELECT Id, Customer_Satisfaction_Rating__c, AccountId, Account.Name
                        FROM Case WHERE ACCOUNTID = :acct.Id LIMIT 1];

        System.assertEquals('TestAcct0', acct.Name);
    }
    
    @isTest static void afterUpdateTest() {
        
        Account acct = [SELECT Id, CSR__c, CS_Rating__c, Account.Name FROM Account WHERE Name='TestAcct0' LIMIT 1];
        Case caseObj = [SELECT Id, Customer_Satisfaction_Rating__c, AccountId, Account.Name
                        FROM Case WHERE ACCOUNTID = :acct.Id LIMIT 1];
        
        caseObj.Customer_Satisfaction_Rating__c = 3;
        caseObj.Status = 'Closed';
        Test.startTest();
        Database.SaveResult result = Database.update(caseObj, false);
        Test.stopTest();
        System.assertEquals(3, caseObj.Customer_Satisfaction_Rating__c);
    }
    
    @isTest static void afterDeleteTest() {
        
        Account acct = [SELECT Id, CSR__c, CS_Rating__c, Account.Name FROM Account WHERE Name='TestAcct0' LIMIT 1];
        Case caseObj = [SELECT Id, Customer_Satisfaction_Rating__c, AccountId, Account.Name
                        FROM Case WHERE ACCOUNTID = :acct.Id LIMIT 1];
        
        caseObj.Customer_Satisfaction_Rating__c = 3;
        caseObj.Status = 'Closed';
        update caseObj;
        Test.startTest();
        Database.DeleteResult result = Database.delete(caseObj, false);
        Test.stopTest();
    }

}